# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7caf3b087a88895c912f2f6ea808712983606069a44db4290ff916e20e01e2014ec9154de695bf82a951aaa1f1c269834ff6351358a8a3ceac3628ee1eefee7d

test:
  secret_key_base: ab2767fdd5aac4bf2e8f84e6086fa2b4913e868223f89998094d4912bc8a3ced3290a50f474fb8ce7eeb93a42668bd7a1ec3de14272531ad7178219b31705513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
